### PR TITLE
Invoke haxe in cwd

### LINKED ISSUE #72: vshaxe's eval-debugger doesn't work with Lix/Haxeshim (Haxe 4RC2, scoped or global Lix-installed Haxe)
I don't know whether this is a `lix` or `haxeshim` issue (or, less-likely a vshaxe `eval-debugger` issue).

* vshaxe v2.8.0
* vscode v1.32.3 (linux)
* Linux Mint 18.3
* Lix 15.3.6
* Haxe 4RC2

I have a local lix scope in my project set to Haxe 4RC2. In vshaxe, there's no custom config for the haxe executable (default is just `haxe`). After `lix download`ing everything, completion works as expected in `vshaxe`.

Here's a dump of my vshaxe settings.json:

`global settings`:
```
{
 "haxe.enableCompilationServer": false
}
```

`workspace settings`:
```
{
  "haxe.displayConfigurations": [["build-frontend.hxml"],["build-backend.hxml"]],
}
```

Then, I have the following launch.json for the workspace, to configure the eval-debugger debugging launch target:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Haxe Interpreter",
			"type": "haxe-eval",
			"request": "launch",
		}
	]
}
```

When I go the `Debug` section of vscode and launch the debug build: 

vshaxe1

It ends up failing with the following message:

`classpath src is not a directory or cannot be read from`

vshaxe2

The `src` directory *is* present in the workspace, it's part of my project's directory's tree:

```
├── app.js
├── build-backend.hxml
├── build-frontend.hxml
├── haxelib.json
├── haxe_libraries
├── makefile
├── node_modules
├── package.json
├── README.md
├── release_haxelib.sh
├── src //<--- here
├── webpack.config.js
└── yarn.lock
```

Also, as you may see, I have two hxmls, as this projects includes code for the frontend and the backend of the app. Right now, `build-backend.hxml` is only a placeholder as I haven't got to implementing it yet, so both files have the following contents:

```
-lib haxe-loader
-lib react

-cp src
-js app.js
-main App

-D react_hot
```

Perhaps this a Haxeshim bug? Any insights and or workarounds would be greatly appreciated.

There's some additional information in the discussion [here](https://pastebin.com/Rc1ivEmG) and [here](https://pastebin.com/1Wv9DPrt).

Thanks!

### PR DESCRIPTION
**Pull request by kevinresol**
Fixes https://github.com/lix-pm/lix.client/issues/72

### CODE REVIEW

**Comment by Gama11** [comment]
But why? We already specify `--cwd`, which seems to work fine for local Haxelib repos.

**Comment by Gama11** [comment]
(and that is also how what the language server does for display requests)

**Comment by kevinresol** [comment]
When lix is installed, the `haxe` command does not point to the haxe compiler binary but haxeshim which is a script that checks for the configured haxe version in `.haxerc` in cwd and invoke the actual haxe compiler. So it has to be invoked in the correct directory (instead of passing the cwd as an arg).

Anyway I think this is more correct as it mimic the behaviour of running the haxe command in cli manually.

**Comment by kevinresol** [comment]
> (and that is also how what the language server does for display requests)

In that case this patch should also be applied there. And perhaps that would solve some lix-related problems.

**Comment by Gama11** [comment]
Well, what confused me is that it seems to work ok for the language server, but not eval-debugger?

@nadako Is there a particular reason we don't just set the cwd / would tha even work for us?

**Comment by kevinresol** [comment]
I guess it "works" because it invoked haxe in lix's global scope instead of the project-specified one? Perhaps that's why there are problems _sometimes_, which might be due to incompatible haxe version with some libraries.

**Comment by kevinresol** [comment]
> Is there a particular reason we don't just set the cwd

It seems to me that it simply because cwd doesn't matter for the haxe compiler (it is the case if the haxe compiler never access the process's cwd). The `--cwd` flag is completely irrelevant in this context.

**Comment by nadako** [comment]
> @nadako Is there a particular reason we don't just set the cwd / would tha even work for us?

I don't remember ^^ But in general, if we ever want to share haxe server across e.g. workspace folders, we'd still need to do `--cmd`.

**Comment by kevinresol** [comment]
> if we ever want to share haxe server across e.g. workspace folders

FWIW, Lix users want to use the project's specified haxe version for each workspace. So unless the haxe version are exactly the same they shouldn't be shared.

**Comment by Gama11** [comment]
Anyway, if this helps, I'll just merge it for now. I don't have a Lix setup, so I trust that it works. :)

**Pull request merged**
